// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login";
  };
  "./routes/dashboard/dashboard.screen.tsx": {
    id: "routes/dashboard/dashboard.screen";
    page: "/";
  };
  "./routes/login/login.screen.tsx": {
    id: "routes/login/login.screen";
    page: "/login";
  };
};